import type { Action } from './types';

const now = new Date();

export function generateMockActions(): Action[] {
  return [
    {
      id: 'act_1',
      kind: 'RISK_ALERT',
      title: 'Constructora Ruiz — presupuesto expira en 24h',
      reason: '€4.200 en riesgo si no se envía recordatorio hoy',
      impact: 4200,
      priority: 'HIGH',
      entity: { type: 'client', id: 'cli_ruiz', name: 'Constructora Ruiz' },
      cta: 'Enviar recordatorio',
      actionUrl: '/quotes/qt_ruiz_001',
      meta: { expiresAt: new Date(now.getTime() + 24 * 60 * 60 * 1000) },
      createdAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
    },
    {
      id: 'act_2',
      kind: 'REVENUE_OPPORTUNITY',
      title: '3 presupuestos sin respuesta > 7 días',
      reason: '€8.750 recuperables con seguimiento activo',
      impact: 8750,
      priority: 'HIGH',
      entity: { type: 'pipeline', id: 'pipe_stale', name: 'Pipeline rezagado' },
      cta: 'Ver presupuestos',
      actionUrl: '/quotes?filter=stale',
      createdAt: new Date(now.getTime() - 4 * 60 * 60 * 1000),
    },
    {
      id: 'act_3',
      kind: 'OPTIMIZE_QUOTE',
      title: 'Presupuesto Estudio Vega — +12% potencial',
      reason: 'IA detecta margen de optimización en materiales',
      impact: 1440,
      priority: 'MEDIUM',
      entity: { type: 'quote', id: 'qt_vega_003', name: 'Estudio Vega' },
      cta: 'Optimizar con IA',
      actionUrl: '/quotes/qt_vega_003/optimize',
      createdAt: new Date(now.getTime() - 6 * 60 * 60 * 1000),
    },
    {
      id: 'act_4',
      kind: 'FOLLOW_UP',
      title: 'Arq. Martinez no abre presupuesto hace 5 días',
      reason: 'Última apertura registrada hace 120h',
      impact: 3200,
      priority: 'MEDIUM',
      entity: { type: 'client', id: 'cli_martinez', name: 'Arq. Martinez' },
      cta: 'Reenviar presupuesto',
      actionUrl: '/quotes/qt_martinez_002',
      createdAt: new Date(now.getTime() - 8 * 60 * 60 * 1000),
    },
    {
      id: 'act_5',
      kind: 'PRIORITIZE',
      title: 'Reordenar pipeline — 2 clientes hot detectados',
      reason: 'Señales de alta intención en López y Fernández',
      impact: 6500,
      priority: 'LOW',
      entity: { type: 'pipeline', id: 'pipe_reorder', name: 'Pipeline general' },
      cta: 'Revisar pipeline',
      actionUrl: '/pipeline',
      createdAt: new Date(now.getTime() - 12 * 60 * 60 * 1000),
    },
    {
      id: 'act_6',
      kind: 'REVENUE_OPPORTUNITY',
      title: 'Cliente recurrente Díaz — sin contacto 30 días',
      reason: 'Histórico: 1 presupuesto/mes, promedio €2.100',
      impact: 2100,
      priority: 'LOW',
      entity: { type: 'client', id: 'cli_diaz', name: 'Reformas Díaz' },
      cta: 'Contactar cliente',
      actionUrl: '/clients/cli_diaz',
      createdAt: new Date(now.getTime() - 24 * 60 * 60 * 1000),
    },
  ];
}
